In [1]:
import pandas as pd

from variables import csv_list

print(csv_list)
for csv in csv_list:
    csv = pd.read_csv(csv)
    print(csv['ciudad'].unique())
    display(csv.info(), csv.head())

['data/clima_donostia.csv', 'data/clima_bilbo.csv', 'data/clima_baiona.csv', 'data/clima_iruna.csv', 'data/clima_gasteiz.csv', 'data/clima_arrasate.csv', 'data/clima_maule.csv']
<StringArray>
['Donostia']
Length: 1, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 31412 entries, 0 to 31411
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 31412 non-null  str
 1   temperature_2m_mean  31411 non-null  float64
 2   temperature_2m_min   31412 non-null  float64
 3   temperature_2m_max   31412 non-null  float64
 4   precipitation_sum    31411 non-null  float64
 5   wind_speed_10m_max   31412 non-null  float64
 6   ciudad               31412 non-null  str
 7   año                  31412 non-null  int64
 8   mes                  31412 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.2 MB

None

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,wind_speed_10m_max,ciudad,año,mes
0,1940-01-01,NaN,4.1,10.0,NaN,24.3,Donostia,1940,1
1,1940-01-02,9.2,7.0,12.1,0.0,33.3,Donostia,1940,1
2,1940-01-03,11.7,10.5,13.1,2.3,35.8,Donostia,1940,1
3,1940-01-04,12.2,10.3,14.7,0.6,28.7,Donostia,1940,1
4,1940-01-05,11.0,8.8,13.0,1.5,9.6,Donostia,1940,1

<StringArray>
['Bilbo']
Length: 1, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 31412 entries, 0 to 31411
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 31412 non-null  str
 1   temperature_2m_mean  31411 non-null  float64
 2   temperature_2m_min   31412 non-null  float64
 3   temperature_2m_max   31412 non-null  float64
 4   precipitation_sum    31411 non-null  float64
 5   wind_speed_10m_max   31412 non-null  float64
 6   ciudad               31412 non-null  str
 7   año                  31412 non-null  int64
 8   mes                  31412 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.2 MB

None

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,wind_speed_10m_max,ciudad,año,mes
0,1940-01-01,NaN,3.7,9.9,NaN,22.8,Bilbo,1940,1
1,1940-01-02,8.4,5.0,13.0,0.0,29.6,Bilbo,1940,1
2,1940-01-03,12.4,10.4,15.6,1.0,31.7,Bilbo,1940,1
3,1940-01-04,12.3,10.3,14.9,1.6,23.1,Bilbo,1940,1
4,1940-01-05,10.9,8.9,14.4,0.9,8.5,Bilbo,1940,1

<StringArray>
['Baiona']
Length: 1, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 31412 entries, 0 to 31411
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 31412 non-null  str
 1   temperature_2m_mean  31411 non-null  float64
 2   temperature_2m_min   31412 non-null  float64
 3   temperature_2m_max   31412 non-null  float64
 4   precipitation_sum    31411 non-null  float64
 5   wind_speed_10m_max   31412 non-null  float64
 6   ciudad               31412 non-null  str
 7   año                  31412 non-null  int64
 8   mes                  31412 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.2 MB

None

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,wind_speed_10m_max,ciudad,año,mes
0,1940-01-01,NaN,1.6,9.2,NaN,20.1,Baiona,1940,1
1,1940-01-02,8.6,4.8,12.6,0.0,24.2,Baiona,1940,1
2,1940-01-03,11.8,10.0,14.3,2.8,25.5,Baiona,1940,1
3,1940-01-04,12.7,10.8,15.2,0.0,26.6,Baiona,1940,1
4,1940-01-05,10.9,8.0,12.5,1.9,14.8,Baiona,1940,1

<StringArray>
['Iruña']
Length: 1, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 31412 entries, 0 to 31411
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 31412 non-null  str
 1   temperature_2m_mean  31411 non-null  float64
 2   temperature_2m_min   31412 non-null  float64
 3   temperature_2m_max   31412 non-null  float64
 4   precipitation_sum    31411 non-null  float64
 5   wind_speed_10m_max   31412 non-null  float64
 6   ciudad               31412 non-null  str
 7   año                  31412 non-null  int64
 8   mes                  31412 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.2 MB

None

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,wind_speed_10m_max,ciudad,año,mes
0,1940-01-01,NaN,-1.5,5.6,NaN,17.6,Iruña,1940,1
1,1940-01-02,3.6,0.3,7.4,0.3,25.2,Iruña,1940,1
2,1940-01-03,7.2,5.9,8.8,4.3,27.6,Iruña,1940,1
3,1940-01-04,7.9,5.8,10.9,2.0,20.5,Iruña,1940,1
4,1940-01-05,7.6,5.6,11.3,2.3,10.0,Iruña,1940,1

<StringArray>
['Gasteiz']
Length: 1, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 31412 entries, 0 to 31411
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 31412 non-null  str
 1   temperature_2m_mean  31411 non-null  float64
 2   temperature_2m_min   31412 non-null  float64
 3   temperature_2m_max   31412 non-null  float64
 4   precipitation_sum    31411 non-null  float64
 5   wind_speed_10m_max   31412 non-null  float64
 6   ciudad               31412 non-null  str
 7   año                  31412 non-null  int64
 8   mes                  31412 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.2 MB

None

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,wind_speed_10m_max,ciudad,año,mes
0,1940-01-01,NaN,-1.3,6.0,NaN,13.5,Gasteiz,1940,1
1,1940-01-02,2.4,-1.4,9.0,0.0,23.2,Gasteiz,1940,1
2,1940-01-03,7.3,5.0,11.0,0.3,22.2,Gasteiz,1940,1
3,1940-01-04,7.0,4.3,11.2,2.5,16.4,Gasteiz,1940,1
4,1940-01-05,7.9,5.4,11.5,1.7,14.0,Gasteiz,1940,1

<StringArray>
['Arrasate']
Length: 1, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 31412 entries, 0 to 31411
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 31412 non-null  str
 1   temperature_2m_mean  31411 non-null  float64
 2   temperature_2m_min   31412 non-null  float64
 3   temperature_2m_max   31412 non-null  float64
 4   precipitation_sum    31411 non-null  float64
 5   wind_speed_10m_max   31412 non-null  float64
 6   ciudad               31412 non-null  str
 7   año                  31412 non-null  int64
 8   mes                  31412 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.2 MB

None

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,wind_speed_10m_max,ciudad,año,mes
0,1940-01-01,NaN,-0.7,6.1,NaN,17.1,Arrasate,1940,1
1,1940-01-02,4.0,0.6,9.1,0.0,25.1,Arrasate,1940,1
2,1940-01-03,8.1,6.5,10.7,1.0,28.1,Arrasate,1940,1
3,1940-01-04,8.0,5.4,12.0,2.2,14.8,Arrasate,1940,1
4,1940-01-05,7.7,4.9,11.9,1.6,8.9,Arrasate,1940,1

<StringArray>
['Maule']
Length: 1, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 31412 entries, 0 to 31411
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 31412 non-null  str
 1   temperature_2m_mean  31411 non-null  float64
 2   temperature_2m_min   31412 non-null  float64
 3   temperature_2m_max   31412 non-null  float64
 4   precipitation_sum    31411 non-null  float64
 5   wind_speed_10m_max   31412 non-null  float64
 6   ciudad               31412 non-null  str
 7   año                  31412 non-null  int64
 8   mes                  31412 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.2 MB

None

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,wind_speed_10m_max,ciudad,año,mes
0,1940-01-01,NaN,0.0,9.2,NaN,7.5,Maule,1940,1
1,1940-01-02,6.0,2.3,11.6,0.0,13.4,Maule,1940,1
2,1940-01-03,9.7,7.1,13.5,2.9,13.7,Maule,1940,1
3,1940-01-04,11.1,8.8,14.8,0.0,17.0,Maule,1940,1
4,1940-01-05,9.1,5.6,12.5,2.9,8.8,Maule,1940,1