In [6]:
import pandas as pd

df_baiona = pd.read_csv('clima_baiona.csv')
df_irunea = pd.read_csv('clima_irunea.csv')
df_vitoria = pd.read_csv('clima_vitoria.csv')

In [7]:
df_baiona = pd.DataFrame(df_baiona)
df_irunea = pd.DataFrame(df_irunea)
df_vitoria = pd.DataFrame(df_vitoria)

In [8]:
display(df_baiona.head(), df_irunea.head(), df_vitoria.head())

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,ciudad,año,mes
0,1940-01-01,NaN,1.6,9.2,NaN,Baiona,1940,1
1,1940-01-02,8.6,4.8,12.6,0.0,Baiona,1940,1
2,1940-01-03,11.8,10.0,14.3,2.8,Baiona,1940,1
3,1940-01-04,12.7,10.8,15.2,0.0,Baiona,1940,1
4,1940-01-05,10.9,8.0,12.5,1.9,Baiona,1940,1

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,ciudad,año,mes
0,1940-01-01,NaN,-1.5,5.6,NaN,Iruñea,1940,1
1,1940-01-02,3.7,0.3,7.4,0.3,Iruñea,1940,1
2,1940-01-03,7.2,5.9,8.8,4.3,Iruñea,1940,1
3,1940-01-04,7.9,5.8,10.9,2.0,Iruñea,1940,1
4,1940-01-05,7.6,5.6,11.3,2.3,Iruñea,1940,1

,time,temperature_2m_mean,temperature_2m_min,temperature_2m_max,precipitation_sum,ciudad,año,mes
0,1990-01-01,5.3,1.8,10.5,3.4,Vitoria,1990,1
1,1990-01-02,4.9,0.1,10.1,0.0,Vitoria,1990,1
2,1990-01-03,5.5,3.9,8.2,1.9,Vitoria,1990,1
3,1990-01-04,5.5,2.6,8.4,0.4,Vitoria,1990,1
4,1990-01-05,3.3,-1.5,10.0,0.0,Vitoria,1990,1

In [13]:
df_baiona.info()

<class 'pandas.DataFrame'>
RangeIndex: 31047 entries, 0 to 31046
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 31047 non-null  str
 1   temperature_2m_mean  31046 non-null  float64
 2   temperature_2m_min   31047 non-null  float64
 3   temperature_2m_max   31047 non-null  float64
 4   precipitation_sum    31046 non-null  float64
 5   ciudad               31047 non-null  str
 6   año                  31047 non-null  int64
 7   mes                  31047 non-null  int64
dtypes: float64(4), int64(2), str(2)
memory usage: 1.9 MB

In [12]:
df_irunea.info()

<class 'pandas.DataFrame'>
RangeIndex: 31047 entries, 0 to 31046
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 31047 non-null  str
 1   temperature_2m_mean  31046 non-null  float64
 2   temperature_2m_min   31047 non-null  float64
 3   temperature_2m_max   31047 non-null  float64
 4   precipitation_sum    31046 non-null  float64
 5   ciudad               31047 non-null  str
 6   año                  31047 non-null  int64
 7   mes                  31047 non-null  int64
dtypes: float64(4), int64(2), str(2)
memory usage: 1.9 MB

In [11]:
df_vitoria.info()

<class 'pandas.DataFrame'>
RangeIndex: 12784 entries, 0 to 12783
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 12784 non-null  str
 1   temperature_2m_mean  12784 non-null  float64
 2   temperature_2m_min   12784 non-null  float64
 3   temperature_2m_max   12784 non-null  float64
 4   precipitation_sum    12784 non-null  float64
 5   ciudad               12784 non-null  str
 6   año                  12784 non-null  int64
 7   mes                  12784 non-null  int64
dtypes: float64(4), int64(2), str(2)
memory usage: 799.1 KB